"""
AgriMetSpider settings for {{ project_name}}

Generated by 'AgriMetStarter.py'

"""

# changed to string
basic_settings = {
	"PROJECT_SETTINGS":{
						"project_name":"",
						"project_path":"",
						"project_setting_path":""
						},

	"DB_SETTINGS": {
					"database_path":"", 
					"database_name":"", 
					},

	"URL_SETTINGS":{
					"baseurl":"https://www.usbr.gov/pn-bin/daily.pl?", 
					"weather_parameters":"MN,MX,MM,PP",
					"format":"csv",
					"start":"",
					"end":"",
					"back":""
					},

	"SCHEDULER_SETTINGS":{
						"MINUTE":"*", 
						"HOUR":"*", 
						"DOM":"*", 
						"MON":"*", 
						"DOW":"*"
						},

	"LOG_SETTINGS":{
					"logfile_name":"",
					"logfile_path":"",
					"logfile_format":"",
					"logfile_datetimefmt":""
					},

	"STATION_SETTINGS":{
					"station_url":"https://www.usbr.gov/pn/agrimet/location.csv",
					"site_ids":"",
					"states":"OR,WA,ID"
					}
}